SUDO : required
services:
    - docker

before_install:
    - docker build -t saikchak/react-test -f ./client/Dockerfile.dev ./client    

script:
    - docker run -e CI=true USERNAME/react-test npm test -- --coverage
    
after_success:
    - docker build -t saikchak/multi-client ./client
    - docker build -t saikchak/multi-nginx  ./nginx
    - docker build -t saikchak/multi-server ./server
    - docker build -t saikchak/multi-worker ./worker

echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin

- docker push saikchak/multi-client
- docker push saikchak/multi-nginx
- docker push saikchak/multi-server
- docker push saikchak/multi-worker